coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto
    patch:
      default:
        target: 0%
        informational: true

ignore:
  - "tests/**/*"
  - "target/**/*"
  - "examples/**/*"